version: '3'
services:
  ssh:
    image: linuxserver/openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=dalongrongdemo #optional
      - USER_NAME=dalong #optional
    volumes:
      - ./config:/config
    ports:
      - "2222:2222"