version: '3'
services:
  githttp:
   image: dalongrong/git-http
   volumes:
    - ./gitrepo:/opt/gitrepo
   ports:
   - "8080:8080"
  ssh:
    image: dalongrong/openssh-server
    build: ./
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=dalongdemo #optional
      - USER_NAME=git #optional
    volumes:
      - ./config:/config
      - ./gitrepo:/opt/gitrepo
    ports:
      - "2222:2222"